service: sls
frameworkVersion: '2'
custom:
    table_names:
      BUS_STOP_TABLE: bus_stop
      USERS_TABLE: users
      BUS_TABLE: bus
    secrets: ${file(secrets.json)}
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    JWT_SECRET: ${self:custom.secrets.JWT_SECRET}
    BUS_STOP_TABLE: ${self:custom.table_names.BUS_STOP_TABLE}
    BUS_TABLE: ${self:custom.table_names.BUS_TABLE}
    REGION: ap-southeast-1
  region: ap-southeast-1
  iamRoleStatements:
   - Effect: "Allow"
     Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
     Resource:
      - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.table_names.BUS_STOP_TABLE}"
      - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.table_names.USERS_TABLE}"
      - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.table_names.BUS_TABLE}"
functions:
  auth:
    handler: auth/authorize.handler
  readBusStop:
    handler: handler.readBusStop
    events:
    - http:
        path: /bus-stops
        method: get
        cors: true
        authorizer:
          name: auth
          resultTtlInSeconds: 0
  getBusStop:
    handler: handler.getBusStop
    events:
    - http:
        path: /bus-stops/{bus_stop_id}
        method: get
        cors: true
        authorizer:
          name: auth
          resultTtlInSeconds: 0
  login:
    handler: auth/login.handler
    events:
    - http:
        method: post
        path: login
        cors: true
  register:
    handler: handler.register
    events:
    - http:
        path: register
        method: post
        cors: true
resources:
  Resources:
    BusStopsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
        - AttributeName: "bus_stop_id"
          AttributeType: "S"
        - AttributeName: "name"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "bus_stop_id"
          KeyType: "HASH"
        - AttributeName: "name"
          KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.table_names.BUS_STOP_TABLE}
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
        - AttributeName: "usernamePrimary"
          AttributeType: "S"
        - AttributeName: "usernameSort"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "usernamePrimary"
          KeyType: "HASH"
        - AttributeName: "usernameSort"
          KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.table_names.USERS_TABLE}
    BusTable:
      Type: AWS::DynamoDB::Table
      Properties:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
        AttributeDefinitions:
        - AttributeName: "bus_id"
          AttributeType: "S"
        - AttributeName: "bus_stop_id"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "bus_id"
          KeyType: "HASH"
        - AttributeName: "bus_stop_id"
          KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.table_names.BUS_TABLE}
